# Generated by Django 5.0.6 on 2024-10-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0004_roverdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoverData',
        ),
    ]
